// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.20.3
// source: apps/pkg/proto/pb_msg/msg.proto

package pb_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送消息请求
type SendMessageArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId   int64  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`       // 发送者id
	ReceiverId int64  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 接收者id
	Body       string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                // 消息体
}

func (x *SendMessageArgs) Reset() {
	*x = SendMessageArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageArgs) ProtoMessage() {}

func (x *SendMessageArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageArgs.ProtoReflect.Descriptor instead.
func (*SendMessageArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageArgs) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageArgs) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// 发送消息响应
type SendMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// 同步消息请求
type SyncUnreadArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
}

func (x *SyncUnreadArgs) Reset() {
	*x = SyncUnreadArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUnreadArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUnreadArgs) ProtoMessage() {}

func (x *SyncUnreadArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUnreadArgs.ProtoReflect.Descriptor instead.
func (*SyncUnreadArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SyncUnreadArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

// 同步消息响应
type SyncUnreadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 定义一个消息体列表
	Messages []*MessageItem `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SyncUnreadReply) Reset() {
	*x = SyncUnreadReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUnreadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUnreadReply) ProtoMessage() {}

func (x *SyncUnreadReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUnreadReply.ProtoReflect.Descriptor instead.
func (*SyncUnreadReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SyncUnreadReply) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 消息体
type MessageItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId      int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId   int64  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime string `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *MessageItem) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 读消息列表请求
type ReadMessagesArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 谁读了消息
}

func (x *ReadMessagesArgs) Reset() {
	*x = ReadMessagesArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesArgs) ProtoMessage() {}

func (x *ReadMessagesArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesArgs.ProtoReflect.Descriptor instead.
func (*ReadMessagesArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMessagesArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

// 读消息列表响应
type ReadMessagesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 返回个 true 就行
}

func (x *ReadMessagesReply) Reset() {
	*x = ReadMessagesReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesReply) ProtoMessage() {}

func (x *ReadMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesReply.ProtoReflect.Descriptor instead.
func (*ReadMessagesReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *ReadMessagesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apps_pkg_proto_pb_msg_msg_proto protoreflect.FileDescriptor

var file_apps_pkg_proto_pb_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0x63, 0x0a, 0x0f, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x29,
	0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x53, 0x79, 0x6e,
	0x63, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0f,
	0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x7c, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x6f, 0x2d, 0x69, 0x6d, 0x2d, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescOnce sync.Once
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescData = file_apps_pkg_proto_pb_msg_msg_proto_rawDesc
)

func file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP() []byte {
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescOnce.Do(func() {
		file_apps_pkg_proto_pb_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pkg_proto_pb_msg_msg_proto_rawDescData)
	})
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescData
}

var file_apps_pkg_proto_pb_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_apps_pkg_proto_pb_msg_msg_proto_goTypes = []any{
	(*SendMessageArgs)(nil),   // 0: pb_msg.SendMessageArgs
	(*SendMessageReply)(nil),  // 1: pb_msg.SendMessageReply
	(*SyncUnreadArgs)(nil),    // 2: pb_msg.SyncUnreadArgs
	(*SyncUnreadReply)(nil),   // 3: pb_msg.SyncUnreadReply
	(*MessageItem)(nil),       // 4: pb_msg.MessageItem
	(*ReadMessagesArgs)(nil),  // 5: pb_msg.ReadMessagesArgs
	(*ReadMessagesReply)(nil), // 6: pb_msg.ReadMessagesReply
}
var file_apps_pkg_proto_pb_msg_msg_proto_depIdxs = []int32{
	4, // 0: pb_msg.SyncUnreadReply.messages:type_name -> pb_msg.MessageItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_pkg_proto_pb_msg_msg_proto_init() }
func file_apps_pkg_proto_pb_msg_msg_proto_init() {
	if File_apps_pkg_proto_pb_msg_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pkg_proto_pb_msg_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_pkg_proto_pb_msg_msg_proto_goTypes,
		DependencyIndexes: file_apps_pkg_proto_pb_msg_msg_proto_depIdxs,
		MessageInfos:      file_apps_pkg_proto_pb_msg_msg_proto_msgTypes,
	}.Build()
	File_apps_pkg_proto_pb_msg_msg_proto = out.File
	file_apps_pkg_proto_pb_msg_msg_proto_rawDesc = nil
	file_apps_pkg_proto_pb_msg_msg_proto_goTypes = nil
	file_apps_pkg_proto_pb_msg_msg_proto_depIdxs = nil
}
